//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cards
    {
        public Cards()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int CardID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime DestroyDate { get; set; }
    
        public virtual ICollection<Order> Order { get; set; }
    }
}
