//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderID { get; set; }
        public int ClientID { get; set; }
        public int RoomID { get; set; }
        public int UserID { get; set; }
        public int CardID { get; set; }
        public System.DateTime CheckIn { get; set; }
        public System.DateTime CheckOut { get; set; }
    
        public virtual Cards Cards { get; set; }
        public virtual Clients Clients { get; set; }
        public virtual Rooms Rooms { get; set; }
        public virtual Users Users { get; set; }
    }
}
