//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rooms
    {
        public Rooms()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int RoomID { get; set; }
        public int Floor { get; set; }
        public int RoomNumber { get; set; }
        public string RoomCategory { get; set; }
        public string RoomStatus { get; set; }
        public decimal Price { get; set; }
    
        public virtual ICollection<Order> Order { get; set; }
    }
}
